-- Create todos table
create table todos (
  id bigint generated by default as identity primary key,
  title text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table todos enable row level security;

-- Create a policy that allows anyone to view todos
create policy "Public todos are viewable by everyone."
  on todos for select
  using (true);

-- Create a policy that allows anyone to insert todos
create policy "Public todos can be inserted by anyone."
  on todos for insert
  with check (true);

-- Create a policy that allows anyone to update todos
create policy "Public todos can be updated by anyone."
  on todos for update
  using (true)
  with check (true);

-- Create a policy that allows anyone to delete todos
create policy "Public todos can be deleted by anyone."
  on todos for delete
  using (true);

-- Create a trigger to update the updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language 'plpgsql';

create trigger update_todos_updated_at
  before update on todos
  for each row
  execute procedure update_updated_at_column();
