version: '2.4'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54325:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres -c 'max_connections=1000' 
      -c 'shared_buffers=256MB' 
      -c 'effective_cache_size=2GB' 
      -c 'work_mem=64MB' 
      -c 'maintenance_work_mem=512MB' 
      -c 'checkpoint_completion_target=0.9' 
      -c 'wal_buffers=16MB' 
      -c 'default_statistics_target=100'
    init: true

  studio:
    image: public.ecr.aws/supabase/studio:2025.06.30-sha-6f5982d
    restart: always
    environment:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "54323:3000"
    depends_on:
      - db
      - rest

  rest:
    image: public.ecr.aws/supabase/postgrest:v12.2.12
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres?sslmode=disable&connect_timeout=10
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMA: public
      PGRST_DB_JWT_SECRET: ${SUPABASE_ANON_KEY}
      PGRST_DB_EXTRA_SEARCH_PATH: public,auth,storage,realtime
      PGRST_DB_POOL: 10
      PGRST_DB_CHANNEL_ENABLED: true
    ports:
      - "54321:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/rest/v1/test_table"]
      interval: 10s
      timeout: 5s
      retries: 5

  realtime:
    image: supabase/realtime:v2.38.0
    restart: always
    environment:
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      JWT_SECRET: ${SUPABASE_ANON_KEY}
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "54324:4000"
    depends_on:
      - db
    entrypoint: "/app/run.sh"
    ulimits:
      nofile:
        soft: 4096
        hard: 4096

volumes:
  postgres_data:
